# Basic Info
title: Assael
description: >
  One of the world’s leading pearl houses, specializing in haute joaillerie and precious stones.
# Base URL is used in the manner that is specified by this guide
# (http://jekyllrb.com/docs/github-pages/) which is to say, it's
# not used at all.
baseurl: ""
url: "https://www.assael.com"

# Professional and social media links
instagram_username: assaelpearls
pinterest_username: assael0106
youtube_channel: https://www.youtube.com/channel/UC3e9q4qYcSJuGjHLh9ydyyA

# Languages and syntax highlighting
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax-highlighter: rouge

# Include static pages.
include:
 - _landingpages

# Blog
# paginate: 2
# paginate_path: "/blog/:num/"

# For Travis CI and gulp
exclude: ["_assets",
          "Gemfile",
          "Gemfile.lock",
          "gulpfile.js",
          "node_modules",
          "package.json"]

# Collections
collections:
  akoya:
    output: true
    _hide_content: true
    permalink: /collections/akoya/:path/
  angela-cummings:
    output: true
    _hide_content: true
    permalink: /collections/angela-cummings/:path/
  classic-assael:
    output: true
    _hide_content: true
    permalink: /collections/classic-assael/:path/
  couture:
    output: true
    _hide_content: true
    permalink: /collections/couture/:path/
  essentials:
    output: true
    _hide_content: true
    permalink: /collections/essentials/:path/
  julie-parker:
    output: true
    _hide_content: true
    permalink: /collections/julie-parker-endangered-species/:path/
  reho-concepts:
    output: true
    _hide_content: true
    permalink: /collections/reho-concepts-for-assael/:path/
  # pieces:
  #   output: true
  #   _hide_content: true
  #   permalink: /pieces/:path/
  # _pages:
  #   output: true
  #   permalink: '/:path/'

defaults:
  -
    scope:
      path: "home.html"
    values:
      title: "Home"
      layout: "default"
      class: "home"
      _hide_content: true
      permalink: "/"
  -
    scope:
      path: "akoya.html"
    values:
      layout: "collection"
      class: "collection"
      permalink: "/collections/akoya/"
  -
    scope:
      path: ""
      type: "akoya"
    values:
      layout: "product"
      class: "product"
  -
    scope:
      path: "classic-assael.html"
    values:
      layout: "collection"
      class: "collection"
      permalink: "/collections/classic-assael/"
  -
    scope:
      path: ""
      type: "classic-assael"
    values:
      layout: "product"
      class: "product"
  -
    scope:
      path: "angela-cummings.html"
    values:
      layout: "collection"
      class: "collection"
      permalink: "/collections/angela-cummings/"
  -
    scope:
      path: ""
      type: "angela-cummings"
    values:
      layout: "product"
      class: "product"
  -
    scope:
      path: "bracelets.html"
    values:
      layout: "collection"
      class: "collection"
      permalink: "/categories/bracelets/"
  -
    scope:
      path: "brooches.html"
    values:
      layout: "collection"
      class: "collection"
      permalink: "/categories/brooches/"
  -
    scope:
      path: "contact.html"
    values:
      layout: "default"
      class: "contact"
      permalink: "/contact/"
  -
    scope:
      path: "couture.html"
    values:
      layout: "collection"
      class: "collection"
      permalink: "/collections/couture/"
  -
    scope:
      path: ""
      type: "couture"
    values:
      layout: "product"
      class: "product"
  -
    scope:
      path: "earrings.html"
    values:
      layout: "collection"
      class: "collection"
      permalink: "/categories/earrings/"
  -
    scope:
      path: "essentials.html"
    values:
      layout: "collection"
      class: "collection"
      permalink: "/collections/essentials/"
  -
    scope:
      path: ""
      type: "essentals"
    values:
      layout: "product"
      class: "product"
  -
    scope:
      path: "julie-parker-endangered-species.html"
    values:
      layout: "collection"
      class: "collection"
      permalink: "/collections/julie-parker-endangered-species/"
  -
    scope:
      path: ""
      type: "julie-parker"
    values:
      layout: "product"
      class: "product"
  -
    scope:
      path: "legacy.html"
    values:
      layout: "default"
      class: "legacy"
      permalink: "/legacy/"
  -
    scope:
      path: "necklaces.html"
    values:
      layout: "collection"
      class: "collection"
      permalink: "/categories/necklaces/"
  -
    scope:
      path: "reho-concepts-for-assael.html"
    values:
      layout: "collection"
      class: "collection"
      permalink: "/collections/reho-concepts-for-assael/"
  -
    scope:
      path: ""
      type: "reho-concepts"
    values:
      layout: "product"
      class: "product"
  -
    scope:
      path: "retailers.html"
    values:
      layout: "default"
      class: "retailers"
      permalink: "/retailers/"
  -
    scope:
      path: "rings.html"
    values:
      layout: "collection"
      class: "collection"
      permalink: "/categories/rings/"
  -
    scope:
      path: "spotlight.html"
    values:
      layout: "default"
      class: "spotlight"
      permalink: "/spotlight/"

# Gems
gems:
  - jekyll-sitemap
  # - jekyll-picture-tag
  # - jekyll-paginate
  # jemoji

# Picture element presets
# picture:
#   source: "uploads/"
#   output: "uploads/processed-img"
#   markup: "picture"
#   presets:
#     collection:
#       attr:
#         itemprop: "image"
#       ppi: [1, 1.5]
#       source_400:
#         media: "(min-width: 400px)"
#         width: "579"
#       source_default:
#         width: "273"
#     spotlight:
#       attr:
#         itemprop: "image"
#       ppi: [1, 1.5]
#       source_1025:
#         media: "(min-width: 1024px)"
#         width: "949"
#       source_668:
#         media: "(min-width: 668px)"
#         width: "675"
#       source_default:
#         width: "331"