# Basic Info
title: Assael
description: >
  One of the world’s leading pearl houses, specializing in haute joaillerie and precious stones.
# Base URL is used in the manner that is specified by this guide
# (http://jekyllrb.com/docs/github-pages/) which is to say, it's
# not used at all.
baseurl: ""
url: "https://www.assael.com"

# Professional and social media links
instagram_username: assaelpearls
pinterest_username: assael0106
youtube_channel: https://www.youtube.com/channel/UC3e9q4qYcSJuGjHLh9ydyyA

# Languages and syntax highlighting
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax-highlighter: rouge

# Include static pages.
include:
 - _landingpages

# Blog
# paginate: 2
# paginate_path: "/blog/:num/"

# For Travis CI and gulp
exclude: ["_assets",
          "Gemfile",
          "Gemfile.lock",
          "gulpfile.js",
          "node_modules",
          "package.json"]

# Collections
collections:
  akoya:
    output: true
    _hide_content: true
    permalink: /collections/akoya/:path/
  angela-cummings:
    output: true
    _hide_content: true
    permalink: /collections/angela-cummings/:path/
  classic-assael:
    output: true
    _hide_content: true
    permalink: /collections/classic-assael/:path/
  couture:
    output: true
    _hide_content: true
    permalink: /collections/couture/:path/
  essentials:
    output: true
    _hide_content: true
    permalink: /collections/essentials/:path/
  julie-parker:
    output: true
    _hide_content: true
    permalink: /collections/julie-parker-endangered-species/:path/
  reho-concepts:
    output: true
    _hide_content: true
    permalink: /collections/reho-concepts-for-assael/:path/
  # pieces:
  #   output: true
  #   _hide_content: true
  #   permalink: /pieces/:path/
  # _pages:
  #   output: true
  #   permalink: '/:path/'

defaults:
  -
    scope:
      path: "akoya.md"
    values:
      layout: "collection"
      class: "collection"
      permalink: "/collections/akoya/"
      _hide_content: true
  -
    scope:
      collection: "akoya"
    values:
      layout: "product"
      class: "product"
  -
    scope:
      path: "angela-cummings.md"
    values:
      layout: "collection"
      class: "collection"
      permalink: "/collections/angela-cummings/"
      _hide_content: true
  -
    scope:
      collection: "angela-cummings"
    values:
      layout: "product"
      class: "product"
  -
    scope:
      path: "bracelets.md"
    values:
      layout: "category"
      class: "collection"
      permalink: "/categories/bracelets/"
      _hide_content: true
  -
    scope:
      path: "brooches.md"
    values:
      layout: "category"
      class: "collection"
      permalink: "/categories/brooches/"
      _hide_content: true
  -
    scope:
      path: "classic-assael.md"
    values:
      layout: "collection"
      class: "collection"
      permalink: "/collections/classic-assael/"
  -
    scope:
      collection: "classic-assael"
    values:
      layout: "product"
      class: "product"
  -
    scope:
      path: "contact.md"
    values:
      layout: "default"
      class: "contact"
      permalink: "/contact/"
  -
    scope:
      path: "couture.md"
    values:
      layout: "collection"
      class: "collection"
      permalink: "/collections/couture/"
      _hide_content: true
  -
    scope:
      collection: "couture"
    values:
      layout: "product"
      class: "product"
  -
    scope:
      path: "earrings.md"
    values:
      layout: "category"
      class: "collection"
      permalink: "/categories/earrings/"
      _hide_content: true
  -
    scope:
      path: "essentials.md"
    values:
      layout: "collection"
      class: "collection"
      permalink: "/collections/essentials/"
      _hide_content: true
  -
    scope:
      collection: "essentials"
    values:
      layout: "product"
      class: "product"
  -
    scope:
      path: "home.html"
    values:
      title: "Home"
      layout: "default"
      class: "home"
      permalink: "/"
      _hide_content: true
  -
    scope:
      path: "julie-parker-endangered-species.md"
    values:
      layout: "collection"
      class: "collection"
      permalink: "/collections/julie-parker-endangered-species/"
      _hide_content: true
  -
    scope:
      collection: "julie-parker"
    values:
      layout: "product"
      class: "product"
  -
    scope:
      path: "legacy.md"
    values:
      layout: "default"
      class: "legacy"
      permalink: "/legacy/"
      _hide_content: true
  -
    scope:
      path: "necklaces.md"
    values:
      layout: "category"
      class: "collection"
      permalink: "/categories/necklaces/"
      _hide_content: true
  -
    scope:
      path: "reho-concepts-for-assael.md"
    values:
      layout: "collection"
      class: "collection"
      permalink: "/collections/reho-concepts-for-assael/"
      _hide_content: true
  -
    scope:
      collection: "reho-concepts"
    values:
      layout: "product"
      class: "product"
  -
    scope:
      path: "retailers.md"
    values:
      layout: "default"
      class: "retailers"
      permalink: "/retailers/"
      _hide_content: true
  -
    scope:
      path: "rings.md"
    values:
      layout: "category"
      class: "collection"
      permalink: "/categories/rings/"
      _hide_content: true
  -
    scope:
      path: "spotlight.md"
    values:
      layout: "default"
      class: "spotlight"
      permalink: "/spotlight/"
      _hide_content: true

# Gems
gems:
  - jekyll-sitemap

