# Basic Info
title: Assael
description: >
  One of the world’s leading pearl houses, specializing in haute joaillerie and precious stones.
# Base URL is used in the manner that is specified by this guide
# (http://jekyllrb.com/docs/github-pages/) which is to say, it's
# not used at all.
baseurl: ""
url: "https://www.assael.com"

# Professional and social media links
instagram_username: assaelpearls
pinterest_username: assael0106
youtube_channel: https://www.youtube.com/channel/UC3e9q4qYcSJuGjHLh9ydyyA

# Languages and syntax highlighting
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax-highlighter: rouge

# Include static pages.
include:
 - _pages

# Blog
# paginate: 2
# paginate_path: "/blog/:num/"

# For Travis CI and gulp
exclude: ["_assets",
          "Gemfile",
          "Gemfile.lock",
          "gulpfile.js",
          "node_modules",
          "package.json"]

# Collections
collections:
  pieces:
    output: true
    permalink: /pieces/:path/
  _pages:
    output: true
    permalink: '/:path/'

defaults:
  -
    scope:
      path: "_pages/home.html"
    values:
      layout: "default"
      class: "home"
      permalink: "/"
  -
    scope:
      type: "pieces"
      path: ""
    values:
      layout: "product"
      class: "product"
  -
    scope:
      path: "_pages/akoya.html"
    values:
      layout: "default"
      class: "collection"
      permalink: "/collections/akoya/"
  -
    scope:
      path: "_pages/classic-assael.html"
    values:
      layout: "default"
      class: "collection"
      permalink: "/collections/classic-assael/"
  -
    scope:
      path: "_pages/angela-cummings.html"
    values:
      layout: "default"
      class: "collection"
      permalink: "/collections/angela-cummings/"
  -
    scope:
      path: "_pages/bracelets.html"
    values:
      layout: "default"
      class: "collection"
      permalink: "/categories/bracelets/"
  -
    scope:
      path: "_pages/brooches.html"
    values:
      layout: "default"
      class: "collection"
      permalink: "/categories/brooches/"
  -
    scope:
      path: "_pages/contact.html"
    values:
      layout: "default"
      class: "contact"
      permalink: "/contact/"
  -
    scope:
      path: "_pages/couture.html"
    values:
      layout: "default"
      class: "collection"
      permalink: "/collections/couture/"
  -
    scope:
      path: "_pages/earrings.html"
    values:
      layout: "default"
      class: "collection"
      permalink: "/categories/earrings/"
  -
    scope:
      path: "_pages/essentials.html"
    values:
      layout: "default"
      class: "collection"
      permalink: "/collections/essentials/"
  -
    scope:
      path: "_pages/julie-parker-endangered-species.html"
    values:
      layout: "default"
      class: "collection"
      permalink: "/collections/julie-parker-endangered-species/"
  -
    scope:
      path: "_pages/legacy.html"
    values:
      layout: "default"
      class: "legacy"
      permalink: "/legacy/"
  -
    scope:
      path: "_pages/necklaces.html"
    values:
      layout: "default"
      class: "collection"
      permalink: "/categories/necklaces/"
  -
    scope:
      path: "_pages/reho-concepts-for-assael.html"
    values:
      layout: "default"
      class: "collection"
      permalink: "/collections/reho-concepts-for-assael/"
  -
    scope:
      path: "_pages/retailers.html"
    values:
      layout: "default"
      class: "retailers"
      permalink: "/retailers/"
  -
    scope:
      path: "_pages/rings.html"
    values:
      layout: "default"
      class: "collection"
      permalink: "/categories/rings/"
  -
    scope:
      path: "_pages/spotlight.html"
    values:
      layout: "default"
      class: "spotlight"
      permalink: "/spotlight/"

# Gems
gems:
  - jekyll-sitemap
  - jekyll-picture-tag
  # - jekyll-paginate
  # jemoji

# Picture element presets
picture:
  source: "assets/img"
  output: "assets/processed-img"
  markup: "picture"
  presets:
    collection:
      attr:
        itemprop: "image"
      ppi: [1, 1.5]
      source_400:
        media: "(min-width: 400px)"
        width: "579"
      source_default:
        width: "273"
    spotlight:
      attr:
        itemprop: "image"
      ppi: [1, 1.5]
      source_1025:
        media: "(min-width: 1024px)"
        width: "949"
      source_668:
        media: "(min-width: 668px)"
        width: "675"
      source_default:
        width: "331"